export const provinsi = [
   { kode: "11", nama: "Aceh" },
   { kode: "12", nama: "Sumatera Utara" },
   { kode: "13", nama: "Sumatera Barat" },
   { kode: "16", nama: "Sumatera Selatan" },
   { kode: "14", nama: "Riau" },
   { kode: "21", nama: "Kepulauan Riau" },
   { kode: "15", nama: "Jambi" },
   { kode: "17", nama: "Bengkulu" },
   { kode: "18", nama: "Lampung" },
   { kode: "19", nama: "Bangka Belitung" },
   { kode: "31", nama: "DKI Jakarta" },
   { kode: "36", nama: "Banten" },
   { kode: "32", nama: "Jawa Barat" },
   { kode: "33", nama: "Jawa Tengah" },
   { kode: "34", nama: "DI Yogyakarta" },
   { kode: "35", nama: "Jawa Timur" },
   { kode: "51", nama: "Bali" },
   { kode: "61", nama: "Kalimantan Barat" },
   { kode: "62", nama: "Kalimantan Tengah" },
   { kode: "63", nama: "Kalimantan Selatan" },
   { kode: "64", nama: "Kalimantan Timur" },
   { kode: "65", nama: "Kalimantan Utara" },
   { kode: "52", nama: "Nusa Tenggara Barat" },
   { kode: "53", nama: "Nusa Tenggara Timur" },
   { kode: "71", nama: "Sulawesi Utara" },
   { kode: "72", nama: "Sulawesi Tengah" },
   { kode: "73", nama: "Sulawesi Selatan" },
   { kode: "74", nama: "Sulawesi Tenggara" },
   { kode: "75", nama: "Gorontalo" },
   { kode: "76", nama: "Sulawesi Barat" },
   { kode: "81", nama: "Maluku" },
   { kode: "82", nama: "Maluku Utara" },
   { kode: "91", nama: "Papua" },
   { kode: "92", nama: "Papua Barat" },
];
