import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MainStoreProvider } from "@/context/main-store";
import { ToggleContextProvider } from "@/context/toggle-context";
import { ListStoreProvider } from "@/context/dropdown-store";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased w-[1440px] mx-auto p-4`}
         >
            <ToggleContextProvider>
               <MainStoreProvider>
                  <ListStoreProvider>{children}</ListStoreProvider>
               </MainStoreProvider>
            </ToggleContextProvider>
         </body>
      </html>
   );
}
